version: '3.4'
networks:
  app:
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    tty: true
    command: 'redis-server --requirepass $REDIS_PASSWORD'
    ports:
      - $REDIS_PORT:6379
    networks:
      - app3
  node:
    container_name: node
    image: node:lts-alpine
    command:
    ports:
      - 8080:$PORT
    networks:
      - app


